version: '3.5'
services:
  frontend:
    image: front_image
    container_name: frontend_container
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile

  backend:
    image: back_image
    container_name: backend_container
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000