version: '3'
services:
  web:
    image: supachott/demo-nginx_image:2.0
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - 7777:80

# PostgresDB
  db:
    image: supachott/demo-postgres_image:1.0
    build:
      context: postgres
      dockerfile: Dockerfile
    container_name: postgres_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    image: supachott/demo-backend_image:1.0
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend_server
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  frontend:
    image: supachott/demo-frontend_image:1.0
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend_server
    ports:
      - 8000:80
    depends_on:
      backend:
        condition: service_healthy

  backend_test:
    image: supachott/demo-backend-testing_image:1.0
    build:
      context: ./backend-testing
      dockerfile: Dockerfile
    volumes:
      - ./backend-testing/test-report:/etc/newman/newman
    depends_on:
      - backend