run_web:
	docker compose up web -db

run_db:
	docker compose up db -d

run_back:
	docker compose up backend -d

run_front:
	docker compose up frontend -d

start_all:
	docker compose up -d --build

down:
	docker compose down